# Generated by Django 4.2.2 on 2023-06-22 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('catalog_number', models.CharField(max_length=10)),
                ('duration', models.TextField()),
                ('price', models.FloatField(max_length=4)),
                ('description', models.TextField()),
                ('artwork_url', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=255)),
                ('biography', models.CharField(max_length=255)),
                ('website_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('submission_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_number', models.IntegerField()),
                ('track_number', models.IntegerField()),
                ('track_title', models.TextField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tzadik_api.album')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('album_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzadik_api.album')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzadik_api.artist')),
            ],
        ),
        migrations.CreateModel(
            name='PerformerInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzadik_api.instrument')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzadik_api.performer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzadik_api.album')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzadik_api.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='selection',
            field=models.ManyToManyField(related_name='orders', through='tzadik_api.OrderedAlbum', to='tzadik_api.album'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ModifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_artist', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
                ('address_street', models.CharField(blank=True, max_length=100)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_state', models.CharField(blank=True, max_length=100)),
                ('address_zipcode', models.CharField(blank=True, max_length=10)),
                ('payment_type', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistperformer', to='tzadik_api.artist')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzadik_api.performer')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzadik_api.album')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzadik_api.performer')),
                ('performer_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzadik_api.performerinstrument')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='tzadik_api.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='tzadik_api.category'),
        ),
        migrations.AddField(
            model_name='album',
            name='performers',
            field=models.ManyToManyField(related_name='albums', to='tzadik_api.performer'),
        ),
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='tzadik_api.status'),
        ),
        migrations.AddField(
            model_name='album',
            name='track',
            field=models.ManyToManyField(related_name='albums', to='tzadik_api.track'),
        ),
    ]
